# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cronometro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label_tempo = QtWidgets.QLabel(Form)
        self.label_tempo.setGeometry(QtCore.QRect(130, 90, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_tempo.setFont(font)
        self.label_tempo.setObjectName("label_tempo")
        self.botao_iniciar = QtWidgets.QPushButton(Form)
        self.botao_iniciar.setGeometry(QtCore.QRect(110, 160, 75, 23))
        self.botao_iniciar.setObjectName("botao_iniciar")
        self.botao_pausar = QtWidgets.QPushButton(Form)
        self.botao_pausar.setGeometry(QtCore.QRect(200, 160, 75, 23))
        self.botao_pausar.setObjectName("botao_pausar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_tempo.setText(_translate("Form", "00:00:00"))
        self.botao_iniciar.setText(_translate("Form", "Iniciar"))
        self.botao_pausar.setText(_translate("Form", "Pausar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
